# Generated by Django 4.2 on 2023-08-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_task_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created',
            field=models.DateField(default='2023-08-03'),
        ),
    ]
